### ISSUE TITLE
Browse Points of Interest in Vigo

### ISSUE THREAD

**Issue by AlbertoBasalo** [AtomicBuilders/turismo-vigo#1]
```yaml
As a: Visitor
  I want to: browse a list of POI
  So that: I can choose one to visit
```
