### ISSUE TITLE
Search by subcategoria / tipo

### ISSUE THREAD

**Issue by AlbertoBasalo** [AtomicBuilders/turismo-vigo#3]
```yaml
As a: Visitor
  I want to: search by subcategoria or tipo
  So that: I can find these kind of POIs
```
