### ISSUE TITLE
Live counter of POIs found

### ISSUE THREAD

**Issue by AlbertoBasalo** [AtomicBuilders/turismo-vigo#4]
```yaml
As a: Visitor
  I want to: see how many POIs
  So that: I can plan my visit
```
