### ISSUE TITLE
Update URL on search

### ISSUE THREAD

**Issue by AlbertoBasalo** [AtomicBuilders/turismo-vigo#5]
```yaml
As a: User
  I want to: save my query on the URL
  So that: I can send it or return to a query
```
