### ISSUE TITLE
Use subcategoria tag as link to filter

### ISSUE THREAD

**Issue by AlbertoBasalo** [AtomicBuilders/turismo-vigo#6]
```yaml
As a: Visitor
  I want to: filter by clicking
  So that: I can do more with less
```
