### ISSUE TITLE
Have a page for each POI

### ISSUE THREAD

**Issue by AlbertoBasalo** [AtomicBuilders/turismo-vigo#7]
```yaml
As a: Visitor
  I want to: get a page for each POI
  So that: see full deatils of a POI
```
